__author__ = 'zhangtao'
# render 前台界面
import json
from django.shortcuts import render
from App import models
from zdCommon import easyuihelp

from zdCommon.sysjson import getMenuList,getMenuListByUser
from zdCommon.dbhelp import fetchSeq

gUI = easyuihelp.EasyuiFieldUI

def indexview(request):
    return render(request, "importhy/index.html")

def logonview(request):
    return render(request, "importhy/logon.html")

def maintabview(request):
    return render(request, "importhy/MainTab.html")

def mainmenutreeview(request):    #
    l_userid = str(request.session['userid'])
    if l_userid == "1":
        menudata = getMenuList()
    else:
        menudata = getMenuListByUser(l_userid)
    return render(request, "importhy/MainMenuTree.html",locals())

def getcommonsearchview(request):
    return render(request, "importhy/component/commonSearchTemplate.html")
def filterview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.FilterHead,field='id')
    datagrid = easyuihelp.EasyuiFieldUI(model=models.FilterHead,field='datagrid',hidden=True)
    filter_type = easyuihelp.EasyuiFieldUI(model=models.FilterHead,field='filter_type')
    filter_name = easyuihelp.EasyuiFieldUI(model=models.FilterHead,field='filter_name',autoforeign=True,foreigndisplayfield='username')
    return render(request, "importhy/component/filterselect.html",locals())
def logview(request):
    return render(request,"importhy/option/logview.html")
def sysmenuview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='id')
    menuname = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='menuname')
    menushowname = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='menushowname')
    parent_id = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='parent_id',autoforeign=True,foreigndisplayfield='menushowname')
    sortno = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='sortno')
    sys_flag = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='sys_flag')
    remark = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='remark')
    return render(request, 'importhy/sysdata/sysmenu.html',locals())
def sysfuncview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.SysFunc,field='id')
    funcname = easyuihelp.EasyuiFieldUI(model=models.SysFunc,field='funcname',width=200)
    ref_tables = easyuihelp.EasyuiFieldUI(model=models.SysFunc,field='ref_tables',width=200)
    remark = easyuihelp.EasyuiFieldUI(model=models.SysFunc,field='remark',width=250)
    return render(request, 'importhy/sysdata/sysfunc.html',locals())
def sysmenufuncview(request):
    menuid = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='id')
    menuname = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='menuname',width=200)
    menu_parent_id = easyuihelp.EasyuiFieldUI(model=models.SysMenu,field='parent_id',autoforeign=True,foreigndisplayfield='menushowname',hidden=True)
    id = easyuihelp.EasyuiFieldUI(model=models.SysMenuFunc,field='id')
    menu_id = easyuihelp.EasyuiFieldUI(model=models.SysMenuFunc,field='menu_id',hidden=True)
    func_id = easyuihelp.EasyuiFieldUI(model=models.SysMenuFunc,field='func_id',autoforeign=True,foreigndisplayfield='funcname',width=200)
    remark = easyuihelp.EasyuiFieldUI(model=models.SysMenuFunc,field='remark',width=200)
    return render(request, 'importhy/sysdata/sysmenufunc.html',locals())
def syscodview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.SysCode,field='id')
    fldEng = easyuihelp.EasyuiFieldUI(model=models.SysCode,field='fld_eng')
    fldChi = easyuihelp.EasyuiFieldUI(model=models.SysCode,field='fld_chi')
    codName = easyuihelp.EasyuiFieldUI(model=models.SysCode,field='cod_name')
    fldExt1 = easyuihelp.EasyuiFieldUI(model=models.SysCode,field='fld_ext1')
    fldExt2 = easyuihelp.EasyuiFieldUI(model=models.SysCode,field='fld_ext2')
    seq = easyuihelp.EasyuiFieldUI(model=models.SysCode,field='seq')
    remark = easyuihelp.EasyuiFieldUI(model=models.SysCode,field='remark')
    return render(request, "importhy/sysdata/syscod.html",locals())
def userview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.User,field='id')
    username = easyuihelp.EasyuiFieldUI(model=models.User,field='username',width=180)
    #password = easyuihelp.EasyuiFieldUI(model=models.User,field='password',hidden=True)
    lock = easyuihelp.EasyuiFieldUI(model=models.User,field='lock')
    remark = easyuihelp.EasyuiFieldUI(model = models.User,field='remark',width=180)
    return render(request, "importhy/basedata/user.html",locals())
def pwupdateview(request):
    return render(request, "importhy/option/pwupdateview.html",locals())
def postview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.Post,field='id')
    postname = easyuihelp.EasyuiFieldUI(model=models.Post,field='postname')
    remark = easyuihelp.EasyuiFieldUI(model=models.Post,field='remark',width=180)
    return render(request, "importhy/basedata/post.html",locals())
def postuserview(request):
    postid = easyuihelp.EasyuiFieldUI(model=models.Post,field='id')
    postname = easyuihelp.EasyuiFieldUI(model=models.Post,field='postname')
    id = easyuihelp.EasyuiFieldUI(model=models.PostUser,field='id')
    post_id = easyuihelp.EasyuiFieldUI(model=models.PostUser,field='post_id',hidden=True)
    user_id = easyuihelp.EasyuiFieldUI(model=models.PostUser,field='user_id',autoforeign=True,foreigndisplayfield='username',foreignexclude={'username':'Admin'})
    remark = easyuihelp.EasyuiFieldUI(model=models.PostUser,field='remark',width=180)
    return render(request, "importhy/basedata/postuser.html",locals())
def postmenufuncview(request):
    postid = easyuihelp.EasyuiFieldUI(model=models.Post,field='id')
    postname = easyuihelp.EasyuiFieldUI(model=models.Post,field='postname')
    return render(request, "importhy/basedata/postmenufunc.html",locals())
def clientview(request):
    idObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='id')
    clientNameObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='client_name',width=200)
    clientFlagObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='client_flag')
    customFlagObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='custom_flag')
    shipcorpFlagObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='ship_corp_flag')
    yardFlagObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='yard_flag')
    portFlagObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='port_flag')
    financialFlagObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='financial_flag')
    landtransflag = easyuihelp.EasyuiFieldUI(model=models.Client,field='landtrans_flag')
    creditflag = easyuihelp.EasyuiFieldUI(model=models.Client,field='credit_flag')
    remarkObj = easyuihelp.EasyuiFieldUI(model=models.Client,field='remark',width=200)
    protocolid = easyuihelp.EasyuiFieldUI(model=models.Client,field='protocol_id',autoforeign=True,foreigndisplayfield='protocol_name')
    return render(request, "yard/basedata/client.html",locals())
def cntrtypeview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.CntrType,field='id')
    cntrtype = easyuihelp.EasyuiFieldUI(model=models.CntrType,field='cntr_type',width=100)
    cntrtypename = easyuihelp.EasyuiFieldUI(model=models.CntrType,field='cntr_type_name',width=180)
    remark = easyuihelp.EasyuiFieldUI(model=models.CntrType,field='remark',width=180)
    return render(request, "importhy/basedata/cntrtype.html",locals())
def actionview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.Action,field='id')
    action_name = easyuihelp.EasyuiFieldUI(model=models.Action,field='action_name')
    #require_flag = easyuihelp.EasyuiFieldUI(model=models.Action,field='require_flag')
    sortno = easyuihelp.EasyuiFieldUI(model=models.Action,field='sortno')
    remark = easyuihelp.EasyuiFieldUI(model=models.Action,field='remark',width=180)
    return render(request, "importhy/basedata/action.html",locals())
def cargoview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.Cargo,field='id')
    cargoname = easyuihelp.EasyuiFieldUI(model=models.Cargo,field='cargo_name')
    remark = easyuihelp.EasyuiFieldUI(model=models.Cargo,field='remark',width=180)
    return render(request, "importhy/basedata/cargo.html",locals())
def cargotypeview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.CargoType,field='id')
    typename = easyuihelp.EasyuiFieldUI(model=models.CargoType,field='type_name')
    remark = easyuihelp.EasyuiFieldUI(model=models.CargoType,field='remark',width=180)
    return render(request, "importhy/basedata/cargotype.html",locals())
def placeview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.Place,field='id')
    placename = easyuihelp.EasyuiFieldUI(model=models.Place,field='place_name')
    remark = easyuihelp.EasyuiFieldUI(model=models.Place,field='remark',width=180)
    return render(request, "importhy/basedata/place.html",locals())

def dispatchview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.Dispatch,field='id')
    place_name = easyuihelp.EasyuiFieldUI(model=models.Dispatch,field='place_name',width=180)
    remark = easyuihelp.EasyuiFieldUI(model=models.Dispatch,field='remark',width=180)
    return render(request, "importhy/basedata/dispatchplace.html",locals())
def feecodview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.FeeCod,field='id')
    fee_name = easyuihelp.EasyuiFieldUI(model=models.FeeCod,field='fee_name')
    pair_flag = easyuihelp.EasyuiFieldUI(model=models.FeeCod,field='pair_flag')
    #protocol_flag = easyuihelp.EasyuiFieldUI(model=models.FeeCod,field='protocol_flag')
    remark = easyuihelp.EasyuiFieldUI(model=models.FeeCod,field='remark',width=180)
    return render(request, "importhy/basedata/feecod.html",locals())
def paytypeview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.PayType,field='id')
    pay_name = easyuihelp.EasyuiFieldUI(model=models.PayType,field='pay_name')
    remark = easyuihelp.EasyuiFieldUI(model=models.PayType,field='remark',width=180)
    return render(request, "importhy/basedata/paytype.html",locals())
def contractview(request):
    seq = str(fetchSeq('seq_html'))
    actionid = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='id')
    actioncontractid = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='contract_id',hidden=True)
    action_id = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='action_id',autoforeign=True,foreigndisplayfield='action_name')
    finish_flag = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='finish_flag')
    finish_time = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='finish_time')
    actionremark = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='remark',width=200)
    cntrid = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='id')
    cntrcontractid = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='contract_id',hidden=True)
    cntr_type = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='cntr_type',autoforeign=True,foreigndisplayfield='cntr_type')
    cntr_num = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='cntr_num')
    check_num = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='check_num')
    cntrremark = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='remark',width=200)
    clientdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='client_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    customdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='custom_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    shipcorpdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='ship_corp_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    portdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='port_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    yarddata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='yard_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    landtransdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='landtrans_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    #checkyarddata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='check_yard_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    #unboxyarddata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='unbox_yard_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    creditdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='credit_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    dispatchdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='dispatch_place',autoforeign=True,foreigndisplayfield='place_name').editor['options']['data'],ensure_ascii = False)
    cargonamedata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_name',autoforeign=True,foreigndisplayfield='cargo_name').editor['options']['data'],ensure_ascii = False)
    cargotypedata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_type',autoforeign=True,foreigndisplayfield='type_name').editor['options']['data'],ensure_ascii = False)
    originplacedata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='origin_place',autoforeign=True,foreigndisplayfield='place_name').editor['options']['data'],ensure_ascii = False)
    display_toolbar = True
    return render(request, "importhy/contract/contractview.html",locals())

def contractqueryview(request):
    seq = str(fetchSeq('seq_html'))
    id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='id')
    bill_no = easyuihelp.EasyuiFieldUI(model=models.Contract,field='bill_no',width=180)
    vslvoy = easyuihelp.EasyuiFieldUI(model=models.Contract,field='vslvoy',width=180)
    contract_no = easyuihelp.EasyuiFieldUI(model=models.Contract,field='contract_no',width=180)
    dispatch_place = easyuihelp.EasyuiFieldUI(model=models.Contract,field='dispatch_place',autoforeign=True,foreigndisplayfield='place_name',width=100)
    cargo_type = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_type',autoforeign=True,foreigndisplayfield='type_name')
    cargo_name = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_name',autoforeign=True,foreigndisplayfield='cargo_name')
    origin_place = easyuihelp.EasyuiFieldUI(model=models.Contract,field='origin_place',autoforeign=True,foreigndisplayfield='place_name')
    custom_title1 = easyuihelp.EasyuiFieldUI(model=models.Contract,field='custom_title1')
    custom_title2 = easyuihelp.EasyuiFieldUI(model=models.Contract,field='custom_title2')
    landtrans_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='landtrans_id',autoforeign=True,foreigndisplayfield='client_name')
    check_yard_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='check_yard_id',autoforeign=True,foreigndisplayfield='client_name')
    unbox_yard_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='unbox_yard_id',autoforeign=True,foreigndisplayfield='client_name')
    credit_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='credit_id',autoforeign=True,foreigndisplayfield='client_name')
    cntr_freedays = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cntr_freedays')
    client_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    cargo_piece = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_piece')
    cargo_weight = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_weight')
    cargo_volume = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_volume')
    booking_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='booking_date')
    pre_inport_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='pre_inport_date')
    in_port_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='in_port_date')
    return_cntr_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='return_cntr_date')
    custom_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='custom_id',autoforeign=True,foreigndisplayfield='client_name')
    ship_corp_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='ship_corp_id',autoforeign=True,foreigndisplayfield='client_name')
    port_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='port_id',autoforeign=True,foreigndisplayfield='client_name')
    yard_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='yard_id',autoforeign=True,foreigndisplayfield='client_name')
    finish_time = easyuihelp.EasyuiFieldUI(model=models.Contract,field='finish_time')
    finish_flag = easyuihelp.EasyuiFieldUI(model=models.Contract,field='finish_flag')
    remark = easyuihelp.EasyuiFieldUI(model=models.Contract,field='remark')
    actionid = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='id')
    actioncontractid = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='contract_id',hidden=True)
    action_id = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='action_id',autoforeign=True,foreigndisplayfield='action_name')
    finish_flag = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='finish_flag')
    finish_time = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='finish_time')
    actionremark = easyuihelp.EasyuiFieldUI(model=models.ContractAction,field='remark',width=200)
    cntrid = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='id')
    cntrcontractid = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='contract_id',hidden=True)
    cntr_type = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='cntr_type',autoforeign=True,foreigndisplayfield='cntr_type')
    cntr_num = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='cntr_num')
    check_num = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='check_num')
    cntrremark = easyuihelp.EasyuiFieldUI(model=models.ContractCntr,field='remark',width=200)
    prefee_id = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='id')
    prefee_contractid = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='contract_id',hidden=True)
    prefee_feetyp = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ',hidden=True)
    prefee_feecod = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_cod',autoforeign=True,foreigndisplayfield='fee_name')
    prefee_client = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    prefee_amount = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount')
    prefee_feetim = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_tim')
    prefee_financialtim = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_financial_tim')
    prefee_lock_flag = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='lock_flag')
    prefee_audit_id = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='audit_id')
    prefee_ex_feeid = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='ex_feeid',hidden=True)
    prefee_create_flag = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='create_flag')
    prefee_remark = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='remark',width=200)
    display_toolbar = False
    return render(request, "importhy/contract/contractqueryview.html",locals())
def contractreportview(request):
    seq = str(fetchSeq('seq_html'))
    id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='id')
    bill_no = easyuihelp.EasyuiFieldUI(model=models.Contract,field='bill_no',width=180)
    current_action = easyuihelp.EasyuiFieldUI(model=models.Action,field='action_name',title='当前动态',displayfield='current_action')
    cntr_sum = easyuihelp.EasyuiFieldUI(model=models.Contract,field='remark',title='箱量',displayfield='cntr_sum',width=150)
    check_num = easyuihelp.EasyuiFieldUI(model=models.Contract,field='remark',title='查验箱量',displayfield='check_num',width=150)
    vslvoy = easyuihelp.EasyuiFieldUI(model=models.Contract,field='vslvoy',width=180)
    contract_no = easyuihelp.EasyuiFieldUI(model=models.Contract,field='contract_no',width=180)
    dispatch_place = easyuihelp.EasyuiFieldUI(model=models.Contract,field='dispatch_place',autoforeign=True,foreigndisplayfield='place_name',width=100)
    cargo_type = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_type',autoforeign=True,foreigndisplayfield='type_name')
    cargo_name = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_name',autoforeign=True,foreigndisplayfield='cargo_name')
    origin_place = easyuihelp.EasyuiFieldUI(model=models.Contract,field='origin_place',autoforeign=True,foreigndisplayfield='place_name')
    custom_title1 = easyuihelp.EasyuiFieldUI(model=models.Contract,field='custom_title1')
    custom_title2 = easyuihelp.EasyuiFieldUI(model=models.Contract,field='custom_title2')
    landtrans_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='landtrans_id',autoforeign=True,foreigndisplayfield='client_name')
    check_yard_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='check_yard_id',autoforeign=True,foreigndisplayfield='client_name')
    unbox_yard_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='unbox_yard_id',autoforeign=True,foreigndisplayfield='client_name')
    credit_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='credit_id',autoforeign=True,foreigndisplayfield='client_name')
    cntr_freedays = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cntr_freedays')
    client_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    cargo_piece = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_piece')
    cargo_weight = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_weight')
    cargo_volume = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_volume')
    booking_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='booking_date')
    pre_inport_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='pre_inport_date')
    in_port_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='in_port_date')
    return_cntr_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='return_cntr_date')
    custom_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='custom_id',autoforeign=True,foreigndisplayfield='client_name')
    ship_corp_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='ship_corp_id',autoforeign=True,foreigndisplayfield='client_name')
    port_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='port_id',autoforeign=True,foreigndisplayfield='client_name')
    yard_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='yard_id',autoforeign=True,foreigndisplayfield='client_name')
    finish_time = easyuihelp.EasyuiFieldUI(model=models.Contract,field='finish_time')
    finish_flag = easyuihelp.EasyuiFieldUI(model=models.Contract,field='finish_flag')
    remark = easyuihelp.EasyuiFieldUI(model=models.Contract,field='remark')
    return render(request, "importhy/contract/contractreportview.html",locals())
def contractgroupreportview(request):
    seq = str(fetchSeq('seq_html'))
    cntr_num = easyuihelp.EasyuiFieldUI(model=models.Contract,field='remark',title='箱量',displayfield='cntr_num',width=150)
    check_num = easyuihelp.EasyuiFieldUI(model=models.Contract,field='remark',title='查验箱量',displayfield='check_num',width=150)
    client_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    cargo_type = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_type',autoforeign=True,foreigndisplayfield='type_name')
    cargo_name = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_name',autoforeign=True,foreigndisplayfield='cargo_name')
    origin_place = easyuihelp.EasyuiFieldUI(model=models.Contract,field='origin_place',autoforeign=True,foreigndisplayfield='place_name')
    clientdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='client_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    return render(request, "importhy/contract/contractgroupreportview.html",locals())
def billsearchview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='id')
    bill_no = easyuihelp.EasyuiFieldUI(model=models.Contract,field='bill_no',width=150)
    client_id = easyuihelp.EasyuiFieldUI(model=models.Contract,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    vslvoy = easyuihelp.EasyuiFieldUI(model=models.Contract,field='vslvoy')
    cargo_name = easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_name')
    in_port_date = easyuihelp.EasyuiFieldUI(model=models.Contract,field='in_port_date',width=150)
    remark = easyuihelp.EasyuiFieldUI(model=models.Contract,field='remark')
    return render(request, "importhy/contract/billsearchcombogrid.html",locals())
def prefeeview(request):
    seq = str(fetchSeq('seq_html'))
    prefee_id = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='id')
    prefee_contractid = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='contract_id',hidden=True)
    prefee_feetyp = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ',hidden=True)
    prefee_feecod = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_cod',autoforeign=True,foreigndisplayfield='fee_name')
    prefee_client = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    prefee_amount = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount')
    prefee_feetim = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_tim')
    prefee_financialtim = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_financial_tim')
    prefee_lock_flag = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='lock_flag',readonly=True)
    prefee_audit_id = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='audit_id',readonly=True)
    prefee_ex_feeid = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='ex_feeid',hidden=True)
    prefee_create_flag = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='create_flag',hidden=True)
    prefee_remark = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='remark',width=200)
    clientdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='client_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    customdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='custom_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    shipcorpdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='ship_corp_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    portdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='port_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    yarddata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='yard_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    landtransdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='landtrans_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    #checkyarddata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='check_yard_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    #unboxyarddata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='unbox_yard_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    creditdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='credit_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    cargonamedata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_name',autoforeign=True,foreigndisplayfield='cargo_name').editor['options']['data'],ensure_ascii = False)
    cargotypedata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='cargo_type',autoforeign=True,foreigndisplayfield='type_name').editor['options']['data'],ensure_ascii = False)
    originplacedata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='origin_place',autoforeign=True,foreigndisplayfield='place_name').editor['options']['data'],ensure_ascii = False)
    dispatchdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='dispatch_place',autoforeign=True,foreigndisplayfield='place_name').editor['options']['data'],ensure_ascii = False)
    display_toolbar = True
    return render(request, "importhy/contract/contractprefeeview.html",locals())
########################### 收费 、 核销 #########
def actfeeview(request):

    idObj = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='id')
    clientIdObj = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    feeTypObj = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='fee_typ')
    amountObj = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='amount')
    invoiceNoObj = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='invoice_no',width=100)
    checkNoObj = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='check_no',width=100)
    acceptno = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='accept_no',width=100)
    payTypeObj = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='pay_type',autoforeign=True,foreigndisplayfield='pay_name')
    feeTimObj = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='fee_tim')
    # audit_id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='audit_id',hidden=True,readonly=True)
    # ex_feeid = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='ex_feeid',hidden=True,readonly=True)
    return render(request, "importhy/fee/actfee.html",locals())
def auditview(request):    # 已收费用核销
    seq = str(fetchSeq('seq_html'))
    funcname = '核销'
    check_flag = True
    actfee_id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='id')
    actfee_client_Id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    actfee_fee_typ = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='fee_typ')
    actfee_amount = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='amount')
    actfee_invoice_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='invoice_no',width=100)
    actfee_check_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='check_no',width=100)
    actfee_accept_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='accept_no',width=100)
    actfee_pay_type = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='pay_type',autoforeign=True,foreigndisplayfield='pay_name')
    actfee_fee_tim = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='fee_tim')
    actfee_ex_feeid = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='ex_feeid',hidden=True)
    actfee_audit_id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='audit_id',hidden=True)
    actfee_remark = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='remark',width=200)
    prefee_id = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='id')
    prefee_contractid = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='contract_id',hidden=True)
    prefee_feetyp = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ')
    prefee_feecod = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_cod',autoforeign=True,foreigndisplayfield='fee_name')
    prefee_client = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name',hidden=True)
    prefee_amount = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount')
    #prefee_feetim = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_tim')
    #prefee_financialtim = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_financial_tim')
    #prefee_lock_flag = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='lock_flag',readonly=True)
    #prefee_audit_id = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='audit_id',readonly=True)
    prefee_remark = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='remark',width=200)
    clientdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    feetypdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ').editor['options']['data'],ensure_ascii = False)
    return render(request, "importhy/fee/auditview.html",locals())
def unauditview(request):    # 取消核销
    seq = str(fetchSeq('seq_html'))
    funcname = '取消核销'
    check_flag = False
    actfee_id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='id')
    actfee_client_Id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    actfee_fee_typ = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='fee_typ')
    actfee_amount = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='amount')
    actfee_invoice_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='invoice_no',width=100)
    actfee_check_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='check_no',width=100)
    actfee_accept_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='accept_no',width=100)
    actfee_pay_type = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='pay_type',autoforeign=True,foreigndisplayfield='pay_name')
    actfee_fee_tim = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='fee_tim',hidden=True)
    actfee_ex_feeid = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='ex_feeid',hidden=True)
    actfee_audit_id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='audit_id',hidden=True)
    actfee_audit_tim = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='audit_tim')
    actfee_remark = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='remark',width=200)
    prefee_id = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='id')
    prefee_contractid = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='contract_id',hidden=True)
    prefee_feetyp = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ')
    prefee_feecod = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_cod',autoforeign=True,foreigndisplayfield='fee_name')
    prefee_client = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name',hidden=True)
    prefee_amount = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount')
    prefee_remark = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='remark',width=200)
    clientdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    feetypdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ').editor['options']['data'],ensure_ascii = False)
    return render(request, "importhy/fee/unauditview.html",locals())
def auditqueryview(request):    # 核销查询
    seq = str(fetchSeq('seq_html'))
    check_flag = False
    clientdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    feetypdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ').editor['options']['data'],ensure_ascii = False)
    audit_amount = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='amount')
    audit_ex_over = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='ex_over',hidden=True)
    audit_tim = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='audit_tim')
    actfee_id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='id')
    actfee_client_Id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name')
    actfee_fee_typ = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='fee_typ')
    actfee_amount = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='amount')
    actfee_invoice_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='invoice_no',width=100)
    actfee_check_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='check_no',width=100)
    actfee_accept_no = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='accept_no',width=100)
    actfee_pay_type = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='pay_type',autoforeign=True,foreigndisplayfield='pay_name')
    actfee_fee_tim = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='fee_tim',hidden=True)
    actfee_ex_feeid = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='ex_feeid',hidden=True)
    actfee_audit_id = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='audit_id',hidden=True)
    actfee_audit_tim = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='audit_tim',hidden=True)
    actfee_remark = easyuihelp.EasyuiFieldUI(model=models.ActFee,field='remark',width=200)
    prefee_id = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='id')
    prefee_contractid = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='contract_id',hidden=True)
    prefee_feetyp = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ')
    prefee_feecod = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_cod',autoforeign=True,foreigndisplayfield='fee_name')
    prefee_client = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name',hidden=True)
    prefee_amount = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount')
    prefee_remark = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='remark',width=200,hidden=True)

    return render(request, "importhy/fee/auditqueryview.html",locals())
def feesheetview(request):
    bill_no = easyuihelp.EasyuiFieldUI(model=models.Contract,field='bill_no',width=180)
    baogan = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='baogan',title='包干费')
    chaoqi = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='chaoqi',title='超期费')
    duicun = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='duicun',title='堆存费')
    banyi = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='banyi',title='搬移费')
    yanhuo = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='yanhuo',title='验货费')
    xunzheng = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='xunzheng',title='熏蒸费')
    changdi = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='changdi',title='场地费')
    tuoche = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='tuoche',title='拖车费')
    zhibao = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='zhibao',title='滞报金')
    qita = easyuihelp.EasyuiFieldUI(model=models.PreFee,field='amount',displayfield='qita',title='其他')
    clientdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.PreFee,field='client_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    feetypdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.PreFee,field='fee_typ').editor['options']['data'],ensure_ascii = False)
    rptdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.RptItem,field='rpt_id',autoforeign=True,foreigndisplayfield='rpt_name').editor['options']['data'],ensure_ascii = False)
    return render(request, "importhy/contract/feesheetview.html",locals())
def filteroptionview(request):
    return render(request, "importhy/component/filternametype.html")
def rptview(request):
    rpt_id = easyuihelp.EasyuiFieldUI(model=models.Rpt,field='id')
    rpt_rptname = easyuihelp.EasyuiFieldUI(model=models.Rpt,field='rpt_name',width=120)
    rptitem_id = easyuihelp.EasyuiFieldUI(model=models.RptItem,field='id')
    rptitem_rptid = easyuihelp.EasyuiFieldUI(model=models.RptItem,field='rpt_id',hidden=True,readonly=True)
    rptitem_itemname = easyuihelp.EasyuiFieldUI(model=models.RptItem,field='item_name',title='项目名称',width=120)
    rptitem_sortno = easyuihelp.EasyuiFieldUI(model=models.RptItem,field='sort_no')
    fee_id = easyuihelp.EasyuiFieldUI(model=models.RptItemFee,field='fee_id',autoforeign=True,foreigndisplayfield='fee_name',title='费用名称',width=180,displayfield='id')
    #fee_feename = easyuihelp.EasyuiFieldUI(model=models.FeeCod,field='fee_name',width=180)
    rptfee_id = easyuihelp.EasyuiFieldUI(model=models.RptItemFee,field='id')
    rptfee_rptid = easyuihelp.EasyuiFieldUI(model=models.RptItemFee,field='rpt_id',hidden=True)
    rptfee_itemid = easyuihelp.EasyuiFieldUI(model=models.RptItemFee,field='item_id',hidden=True)
    rptfee_feeid = easyuihelp.EasyuiFieldUI(model=models.RptItemFee,field='fee_id',autoforeign=True,foreigndisplayfield='fee_name',title='费用名称',width=180)
    rptfee_feetyp = easyuihelp.EasyuiFieldUI(model=models.RptItemFee,field='fee_typ')
    return render(request, "importhy/fee/rptview.html",locals())
def protocolfeecreateview(request):
    clientdata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.Contract,field='client_id',autoforeign=True,foreigndisplayfield='client_name').editor['options']['data'],ensure_ascii = False)
    return render(request, "importhy/fee/protocolfeeview.html",locals())
def protocolview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.Protocol,field='id')
    protocol_name = easyuihelp.EasyuiFieldUI(model=models.Protocol,field='protocol_name')
    write_date = easyuihelp.EasyuiFieldUI(model=models.Protocol,field='write_date')
    validate_date = easyuihelp.EasyuiFieldUI(model=models.Protocol,field='validate_date')
    remark = easyuihelp.EasyuiFieldUI(model=models.Protocol,field='remark',width=200)
    return render(request, "importhy/protocol/protocolview.html",locals())
def protocolfeeeleview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.FeeEle,field='id')
    ele_name = easyuihelp.EasyuiFieldUI(model=models.FeeEle,field='ele_name')
    init_data_sql = easyuihelp.EasyuiFieldUI(model=models.FeeEle,field='init_data_sql')
    remark = easyuihelp.EasyuiFieldUI(model=models.Protocol,field='remark',width=200)
    return render(request, "importhy/protocol/protocoleleview.html",locals())
def protocolfeeelelovview(request):
    ele_name = easyuihelp.EasyuiFieldUI(model=models.FeeEle,field='ele_name')
    id = easyuihelp.EasyuiFieldUI(model=models.FeeEleLov,field='id')
    ele_id = easyuihelp.EasyuiFieldUI(model=models.FeeEleLov,field='ele_id',hidden=True)
    lov_cod = easyuihelp.EasyuiFieldUI(model=models.FeeEleLov,field='lov_cod')
    lov_name = easyuihelp.EasyuiFieldUI(model=models.FeeEleLov,field='lov_name')
    remark = easyuihelp.EasyuiFieldUI(model=models.FeeEleLov,field='remark',width=200)
    return render(request, "importhy/protocol/protocolfeeelelovview.html",locals())

def protocolmodview(request):
    id = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='id')
    mod_name = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='mod_name')
    col_1 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_1',autoforeign=True,foreigndisplayfield='ele_name')
    col_2 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_2',autoforeign=True,foreigndisplayfield='ele_name')
    col_3 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_3',autoforeign=True,foreigndisplayfield='ele_name')
    col_4 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_4',autoforeign=True,foreigndisplayfield='ele_name')
    col_5 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_5',autoforeign=True,foreigndisplayfield='ele_name')
    col_6 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_6',autoforeign=True,foreigndisplayfield='ele_name')
    col_7 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_7',autoforeign=True,foreigndisplayfield='ele_name')
    col_8 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_8',autoforeign=True,foreigndisplayfield='ele_name')
    col_9 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_9',autoforeign=True,foreigndisplayfield='ele_name')
    col_10 = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='col_10',autoforeign=True,foreigndisplayfield='ele_name')
    mod_descript = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='mod_descript')
    deal_process = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='deal_process')
    remark = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='remark',width=200)
    return render(request, "importhy/protocol/protocolmodview.html",locals())
def protocolfeemodview(request):
    protocol_id = easyuihelp.EasyuiFieldUI(model=models.Protocol,field='id')
    protocol_protocol_name = easyuihelp.EasyuiFieldUI(model=models.Protocol,field="protocol_name",width=180)
    fee_id = easyuihelp.EasyuiFieldUI(model=models.FeeCod,field='id')
    fee_fee_name = easyuihelp.EasyuiFieldUI(model=models.FeeCod,field='fee_name',width=180)
    feemod_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='id')
    feemod_protocol_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='protocol_id',hidden=True)
    feemod_fee_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='fee_id',hidden=True)
    feemod_mod_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='mod_id',autoforeign=True,foreigndisplayfield='mod_name')
    #feemod_sort_no = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='sort_no')
    #feemod_active_flag = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='active_flag')
    mod_id = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='id')
    mod_mod_name = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='mod_name')
    mod_mod_descript = easyuihelp.EasyuiFieldUI(model=models.FeeMod,field='mod_descript',readonly=True,hidden=True)
    return render(request, "importhy/protocol/protocolmodmanagerview.html",locals())
def protocolratview(request):
    protocol_id = easyuihelp.EasyuiFieldUI(model=models.Protocol,field='id')
    protocol_protocol_name = easyuihelp.EasyuiFieldUI(model=models.Protocol,field="protocol_name",width=180)
    feemod_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='id')
    feemod_protocol_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='protocol_id',hidden=True)
    feemod_fee_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='fee_id',autoforeign=True,foreigndisplayfield='fee_name',hidden=True)
    feemod_mod_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolMod,field='mod_id',autoforeign=True,foreigndisplayfield='mod_name')
    rat_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolFeeRat,field='id')
    rat_protocol_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolFeeRat,field='protocol_id',hidden=True,readonly=True)
    rat_fee_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolFeeRat,field='fee_id',hidden=True,readonly=True)
    rat_mod_id = easyuihelp.EasyuiFieldUI(model=models.ProtocolFeeRat,field='mod_id',hidden=True,readonly=True)
    rat_feerat = easyuihelp.EasyuiFieldUI(model=models.ProtocolFeeRat,field='fee_rat')
    rat_discountrat = easyuihelp.EasyuiFieldUI(model=models.ProtocolFeeRat,field='discount_rat')
    return render(request, "importhy/protocol/protocolratview.html",locals())
def protocolratcopyview(request):
    protocoldata = json.dumps(easyuihelp.EasyuiFieldUI(model=models.ProtocolFeeRat,field='protocol_id',autoforeign=True,foreigndisplayfield='protocol_name').editor['options']['data'],ensure_ascii = False)
    return render(request, "importhy/protocol/protocolratcopyview.html",locals())


'''
from zdCommon import easyuihelp
from App import models
id = easyuihelp.EasyuiFieldUI(model=models.FilterHead,field='id')
'''